apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.component_id }}-preprod
  namespace: alex-gitops
  labels:
    app: ${{ values.component_id }}-preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.component_id }}-preprod
  template:
    metadata:
      labels:
       app: ${{ values.component_id }}-preprod
    spec:
      containers:
        - name: container
          image: quay.io/alexmalo/devhub-demo:${{ values.component_id }}-latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP          
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
