apiVersion: v1
kind: Service
metadata:
  name:  ${{ values.component_id }}-preprod
  namespace: alex-gitops
  labels:
    app: ${{ values.component_id }}-preprod
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ${{ values.component_id }}-preprod
