apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: '${{ values.repoName }}'
  owner: rhdh
  title: '${{ values.name }}'
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: ${{ values.projectName }}/${{ values.repoName }}
  links:
    - url: https://devspaces.apps.cluster-lpq8z.sandbox2416.opentlc.com/#git@ssh.dev.azure.com:v3/${{ values.orgName }}/${{ values.projectName }}/${{ values.repoName }}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: vscode://vscode.git/clone?url=git@ssh.dev.azure.com:v3/${{ values.orgName }}/${{ values.projectName }}/${{ values.repoName }}
      title: Local dev (VS Code)
      icon: web
spec:
  type: ${{ values.applicationType }}
  lifecycle: production
  owner: rhdh
