apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: '${{ values.repoName }}'
  owner: user1
  title: '${{ values.name }}'
  {%- if values.description %}
  description: '${{ values.description }}'
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    #dev.azure.com/project-repo: ${{ values.projectName }}/${{ values.repoName }}
    github.com/project-slug: demo-malolab/${{ values.repoName }}
    quay.io/repository-slug: alexmalo/devhub-demo
    argocd/app-selector: backstage-name=${{ values.repoName }}
    backstage.io/kubernetes-id: ${{ values.repoName }}-dev
  links:
    - url: http://${{ values.repoName }}-dev-alex-gitops.apps.ocp.malo.lab/
      title: Dev External Route
      icon: web
    # - url: https://devspaces.apps.cluster-lpq8z.sandbox2416.opentlc.com/#https://${{ values.orgName }}@dev.azure.com/${{ values.orgName }}/${{ values.projectName }}/_git/${{ values.repoName }}
    #   title: OpenShift Dev Spaces (VS Code)
    #   icon: web
    - url: vscode://vscode.git/clone?url=git@github.com:alexandremalo/${{ values.repoName }}.git
      title: Local dev (VS Code)
      icon: web
    - url: https://github.com/alexandremalo/${{ values.repoName }}-gitops
      title: Gitops Manifests
      icon: web
spec:
  type: ${{ values.applicationType }}
  lifecycle: production
  owner: architects
  providesApis:
    - ${{ values.repoName }}

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: '${{ values.repoName }}'
  {%- if values.description %}
  description: '${{ values.description }}'
  {%- endif %}
spec:
  type: openapi
  lifecycle: production
  owner: architects
  definition:
    $text: ./openapi.yaml

