apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: '${{ values.repoName }}'
  owner: user1
  title: '${{ values.name }}'
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: ${{ values.projectName }}/${{ values.repoName }}
    quay.io/repository-slug: ${{ values.orgName }}/${{ values.repoName }}
  links:
    - url: https://devspaces.apps.cluster-lpq8z.sandbox2416.opentlc.com/#https://${{ values.orgName }}@dev.azure.com/${{ values.orgName }}/${{ values.projectName }}/_git/${{ values.repoName }}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: vscode://vscode.git/clone?url=git@ssh.dev.azure.com:v3/${{ values.orgName }}/${{ values.projectName }}/${{ values.repoName }}
      title: Local dev (VS Code)
      icon: web
spec:
  type: ${{ values.applicationType }}
  lifecycle: production
  owner: rhdh

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: '${{ values.repoName }}'
  description: ${{ values.description }}
spec:
  type: openapi
  lifecycle: production
  owner: user1
  definition:
    $text: ./openapi.yaml

