apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: '${{ values.repoName }}'
  owner: rhdh
  title: '${{ values.name }}'
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: ${{ values.orgName }}/${{ values.repoName }}
spec:
  type: ${{ values.applicationType }}
  lifecycle: production
