parameters:
- name: environment
  displayName: Environment to promote
  type: string
  default: preprod
  values:
  - preprod
  - prod
- name: tag
  displayName: Version to promote
  type: string
  default: v1.0

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
   git config --global user.email pipeline@demo.com & git config --global user.name "Pipeline"
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
   git checkout -b main
   promote_env_tag=${{ parameters.tag }}
   promote_env_name=${{ parameters.environment }}
   sed "24s/.*/        value: ${promote_env_tag}/" argocd/demo-api-argocd-app-${promote_env_name}.yaml > argocd/demo-api-argocd-app-${promote_env_name}-temp.yaml
   cat argocd/demo-api-argocd-app-${promote_env_name}-temp.yaml > argocd/demo-api-argocd-app-${promote_env_name}.yaml
   rm argocd/demo-api-argocd-app-${promote_env_name}-temp.yaml
   git add .
   git commit -m "deployment $(Build.BuildNumber)"
   git push --set-upstream origin main
  displayName: Update deploy file
  workingDirectory: $(System.DefaultWorkingDirectory)
